//
//  VideoData.swift
//  YTPlayerV2
//
//  Created by Евгений Маглена on 10.02.2023.
//

import Foundation

struct VideoData: Codable {
    let kind,etag: String
    let items: [VideoItems]
    
}
struct VideoItems: Codable {
    let kind,etag,id: String
    let snippet: Snippet
    let statistics: VideoStatistics
}

/*
 {
     "kind": "youtube#videoListResponse",
     "etag": "E3PDaDkUuqYbJL-sT09RL1yWIQ4",
     "items": [
         {
             "kind": "youtube#video",
             "etag": "dbdhAhs9YiRJocz3l2tvLRJtd-Y",
             "id": "gWCYyLiF45U",
             "snippet": {
                 "publishedAt": "2015-06-09T12:53:17Z",
                 "channelId": "UCN2AOz-HUCZ5zd_E3vmAlSQ",
                 "title": "Volition",
                 "description": "Provided to YouTube by IDOL\n\nVolition · Keluar\n\nZone 22: Panguna - EP\n\n℗ Zone\n\nReleased on: 2015-06-08\n\nLyricist: Alison Lewis\nLyricist: Jonas Förster\nComposer: Alison Lewis\nComposer: Jonas Förster\n\nAuto-generated by YouTube.",
                 "thumbnails": {
                     "default": {
                         "url": "https://i.ytimg.com/vi/gWCYyLiF45U/default.jpg",
                         "width": 120,
                         "height": 90
                     },
                     "medium": {
                         "url": "https://i.ytimg.com/vi/gWCYyLiF45U/mqdefault.jpg",
                         "width": 320,
                         "height": 180
                     },
                     "high": {
                         "url": "https://i.ytimg.com/vi/gWCYyLiF45U/hqdefault.jpg",
                         "width": 480,
                         "height": 360
                     },
                     "standard": {
                         "url": "https://i.ytimg.com/vi/gWCYyLiF45U/sddefault.jpg",
                         "width": 640,
                         "height": 480
                     },
                     "maxres": {
                         "url": "https://i.ytimg.com/vi/gWCYyLiF45U/maxresdefault.jpg",
                         "width": 1280,
                         "height": 720
                     }
                 },
                 "channelTitle": "Keluar - Topic",
                 "tags": [
                     "Keluar",
                     "Zone",
                     "22:",
                     "Panguna",
                     "EP",
                     "Volition"
                 ],
                 "categoryId": "10",
                 "liveBroadcastContent": "none",
                 "localized": {
                     "title": "Volition",
                     "description": "Provided to YouTube by IDOL\n\nVolition · Keluar\n\nZone 22: Panguna - EP\n\n℗ Zone\n\nReleased on: 2015-06-08\n\nLyricist: Alison Lewis\nLyricist: Jonas Förster\nComposer: Alison Lewis\nComposer: Jonas Förster\n\nAuto-generated by YouTube."
                 }
             },
             "statistics": {
                 "viewCount": "8755",
                 "likeCount": "188",
                 "favoriteCount": "0",
                 "commentCount": "0"
             }
         }
     ],
     "pageInfo": {
         "totalResults": 1,
         "resultsPerPage": 1
     }
 }
 */
